//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.12 at 11:15:35 AM BST 
//


package com.astrium.hmas.bean.catalogue;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.astrium.hmas.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Date_QNAME = new QName("http://purl.org/dc/elements/1.1/", "date");
    private final static QName _ItemsPerPage_QNAME = new QName("http://a9.com/-/spec/opensearch/1.1/", "itemsPerPage");
    private final static QName _StartIndex_QNAME = new QName("http://a9.com/-/spec/opensearch/1.1/", "startIndex");
    private final static QName _TotalResults_QNAME = new QName("http://a9.com/-/spec/opensearch/1.1/", "totalResults");
    private final static QName _EarthObservationMetaDataPropertyEarthObservationMetaDataProcessingProcessingInformation_QNAME = new QName("http://www.opengis.net/eop/2.0", "ProcessingInformation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.astrium.hmas.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TimePeriod }
     * 
     */
    public TimePeriod createTimePeriod() {
        return new TimePeriod();
    }

    /**
     * Create an instance of {@link Feed.Generator }
     * 
     */
    public Feed.Generator createFeedGenerator() {
        return new Feed.Generator();
    }

    /**
     * Create an instance of {@link Footprint }
     * 
     */
    public Footprint createFootprint() {
        return new Footprint();
    }

    /**
     * Create an instance of {@link ObservedProperty }
     * 
     */
    public ObservedProperty createObservedProperty() {
        return new ObservedProperty();
    }

    /**
     * Create an instance of {@link EarthObservation.MetaDataProperty.EarthObservationMetaData }
     * 
     */
    public EarthObservation.MetaDataProperty.EarthObservationMetaData createEarthObservationMetaDataPropertyEarthObservationMetaData() {
        return new EarthObservation.MetaDataProperty.EarthObservationMetaData();
    }

    /**
     * Create an instance of {@link EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing.ProcessingInformation }
     * 
     */
    public EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing.ProcessingInformation createEarthObservationMetaDataPropertyEarthObservationMetaDataProcessingProcessingInformation() {
        return new EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing.ProcessingInformation();
    }

    /**
     * Create an instance of {@link MultiSurface.SurfaceMember.Polygon.Exterior }
     * 
     */
    public MultiSurface.SurfaceMember.Polygon.Exterior createMultiSurfaceSurfaceMemberPolygonExterior() {
        return new MultiSurface.SurfaceMember.Polygon.Exterior();
    }

    /**
     * Create an instance of {@link EarthObservationEquipment.AcquisitionParameters.Acquisition }
     * 
     */
    public EarthObservationEquipment.AcquisitionParameters.Acquisition createEarthObservationEquipmentAcquisitionParametersAcquisition() {
        return new EarthObservationEquipment.AcquisitionParameters.Acquisition();
    }

    /**
     * Create an instance of {@link EarthObservation.MetaDataProperty.EarthObservationMetaData.ArchivedIn }
     * 
     */
    public EarthObservation.MetaDataProperty.EarthObservationMetaData.ArchivedIn createEarthObservationMetaDataPropertyEarthObservationMetaDataArchivedIn() {
        return new EarthObservation.MetaDataProperty.EarthObservationMetaData.ArchivedIn();
    }

    /**
     * Create an instance of {@link FeatureOfInterest }
     * 
     */
    public FeatureOfInterest createFeatureOfInterest() {
        return new FeatureOfInterest();
    }

    /**
     * Create an instance of {@link EarthObservation.MetaDataProperty.EarthObservationMetaData.DownlinkedTo.DownlinkInformation }
     * 
     */
    public EarthObservation.MetaDataProperty.EarthObservationMetaData.DownlinkedTo.DownlinkInformation createEarthObservationMetaDataPropertyEarthObservationMetaDataDownlinkedToDownlinkInformation() {
        return new EarthObservation.MetaDataProperty.EarthObservationMetaData.DownlinkedTo.DownlinkInformation();
    }

    /**
     * Create an instance of {@link EarthObservation.MetaDataProperty }
     * 
     */
    public EarthObservation.MetaDataProperty createEarthObservationMetaDataProperty() {
        return new EarthObservation.MetaDataProperty();
    }

    /**
     * Create an instance of {@link TimeInstant }
     * 
     */
    public TimeInstant createTimeInstant() {
        return new TimeInstant();
    }

    /**
     * Create an instance of {@link EarthObservationEquipment.Platform }
     * 
     */
    public EarthObservationEquipment.Platform createEarthObservationEquipmentPlatform() {
        return new EarthObservationEquipment.Platform();
    }

    /**
     * Create an instance of {@link MultiSurface }
     * 
     */
    public MultiSurface createMultiSurface() {
        return new MultiSurface();
    }

    /**
     * Create an instance of {@link EarthObservationEquipment.Instrument }
     * 
     */
    public EarthObservationEquipment.Instrument createEarthObservationEquipmentInstrument() {
        return new EarthObservationEquipment.Instrument();
    }

    /**
     * Create an instance of {@link Feed.Entry }
     * 
     */
    public Feed.Entry createFeedEntry() {
        return new Feed.Entry();
    }

    /**
     * Create an instance of {@link Footprint.MultiExtentOf }
     * 
     */
    public Footprint.MultiExtentOf createFootprintMultiExtentOf() {
        return new Footprint.MultiExtentOf();
    }

    /**
     * Create an instance of {@link Feed.Entry.Content }
     * 
     */
    public Feed.Entry.Content createFeedEntryContent() {
        return new Feed.Entry.Content();
    }

    /**
     * Create an instance of {@link MultiSurface.SurfaceMember }
     * 
     */
    public MultiSurface.SurfaceMember createMultiSurfaceSurfaceMember() {
        return new MultiSurface.SurfaceMember();
    }

    /**
     * Create an instance of {@link EarthObservationEquipment.Sensor }
     * 
     */
    public EarthObservationEquipment.Sensor createEarthObservationEquipmentSensor() {
        return new EarthObservationEquipment.Sensor();
    }

    /**
     * Create an instance of {@link Feed.Subtitle }
     * 
     */
    public Feed.Subtitle createFeedSubtitle() {
        return new Feed.Subtitle();
    }

    /**
     * Create an instance of {@link EarthObservation.MetaDataProperty.EarthObservationMetaData.ArchivedIn.ArchivingInformation }
     * 
     */
    public EarthObservation.MetaDataProperty.EarthObservationMetaData.ArchivedIn.ArchivingInformation createEarthObservationMetaDataPropertyEarthObservationMetaDataArchivedInArchivingInformation() {
        return new EarthObservation.MetaDataProperty.EarthObservationMetaData.ArchivedIn.ArchivingInformation();
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link EarthObservationResult }
     * 
     */
    public EarthObservationResult createEarthObservationResult() {
        return new EarthObservationResult();
    }

    /**
     * Create an instance of {@link EarthObservationEquipment.Instrument.Instrument }
     * 
     */
    public EarthObservationEquipment.Instrument.InstrumentType createEarthObservationEquipmentInstrumentInstrument() {
        return new EarthObservationEquipment.Instrument.InstrumentType();
    }

    /**
     * Create an instance of {@link EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing }
     * 
     */
    public EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing createEarthObservationMetaDataPropertyEarthObservationMetaDataProcessing() {
        return new EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link EarthObservationEquipment.Sensor.Sensor }
     * 
     */
    public EarthObservationEquipment.Sensor.SensorType createEarthObservationEquipmentSensorSensor() {
        return new EarthObservationEquipment.Sensor.SensorType();
    }

    /**
     * Create an instance of {@link com.astrium.hmas.bean.catalogue.ProcessingInformation }
     * 
     */
    public com.astrium.hmas.bean.catalogue.ProcessingInformation createProcessingInformation() {
        return new com.astrium.hmas.bean.catalogue.ProcessingInformation();
    }

    /**
     * Create an instance of {@link com.astrium.hmas.bean.catalogue.Polygon }
     * 
     */
    public com.astrium.hmas.bean.catalogue.Polygon createPolygon() {
        return new com.astrium.hmas.bean.catalogue.Polygon();
    }

    /**
     * Create an instance of {@link Feed.Link }
     * 
     */
    public Feed.Link createFeedLink() {
        return new Feed.Link();
    }

    /**
     * Create an instance of {@link Where }
     * 
     */
    public Where createWhere() {
        return new Where();
    }

    /**
     * Create an instance of {@link Procedure }
     * 
     */
    public Procedure createProcedure() {
        return new Procedure();
    }

    /**
     * Create an instance of {@link Feed }
     * 
     */
    public Feed createFeed() {
        return new Feed();
    }

    /**
     * Create an instance of {@link EarthObservationEquipment.Sensor.Sensor.WavelengthInformation }
     * 
     */
    public EarthObservationEquipment.Sensor.SensorType.WavelengthInformation createEarthObservationEquipmentSensorSensorWavelengthInformation() {
        return new EarthObservationEquipment.Sensor.SensorType.WavelengthInformation();
    }

    /**
     * Create an instance of {@link MultiSurface.SurfaceMember.Polygon.Exterior.LinearRing }
     * 
     */
    public MultiSurface.SurfaceMember.Polygon.Exterior.LinearRing createMultiSurfaceSurfaceMemberPolygonExteriorLinearRing() {
        return new MultiSurface.SurfaceMember.Polygon.Exterior.LinearRing();
    }

    /**
     * Create an instance of {@link EarthObservation.MetaDataProperty.EarthObservationMetaData.DownlinkedTo }
     * 
     */
    public EarthObservation.MetaDataProperty.EarthObservationMetaData.DownlinkedTo createEarthObservationMetaDataPropertyEarthObservationMetaDataDownlinkedTo() {
        return new EarthObservation.MetaDataProperty.EarthObservationMetaData.DownlinkedTo();
    }

    /**
     * Create an instance of {@link PhenomenonTime }
     * 
     */
    public PhenomenonTime createPhenomenonTime() {
        return new PhenomenonTime();
    }

    /**
     * Create an instance of {@link Feed.Entry.Link }
     * 
     */
    public Feed.Entry.Link createFeedEntryLink() {
        return new Feed.Entry.Link();
    }

    /**
     * Create an instance of {@link EarthObservationEquipment.AcquisitionParameters }
     * 
     */
    public EarthObservationEquipment.AcquisitionParameters createEarthObservationEquipmentAcquisitionParameters() {
        return new EarthObservationEquipment.AcquisitionParameters();
    }

    /**
     * Create an instance of {@link EarthObservationEquipment.Platform.Platform }
     * 
     */
    public EarthObservationEquipment.Platform.PlatformType createEarthObservationEquipmentPlatformPlatform() {
        return new EarthObservationEquipment.Platform.PlatformType();
    }

    /**
     * Create an instance of {@link EarthObservationEquipment.Sensor.Sensor.WavelengthInformation.WavelengthInformation }
     * 
     */
    public EarthObservationEquipment.Sensor.SensorType.WavelengthInformation.WavelengthInformationType createEarthObservationEquipmentSensorSensorWavelengthInformationWavelengthInformation() {
        return new EarthObservationEquipment.Sensor.SensorType.WavelengthInformation.WavelengthInformationType();
    }

    /**
     * Create an instance of {@link ResultTime }
     * 
     */
    public ResultTime createResultTime() {
        return new ResultTime();
    }

    /**
     * Create an instance of {@link MultiSurface.SurfaceMember.Polygon }
     * 
     */
    public MultiSurface.SurfaceMember.Polygon createMultiSurfaceSurfaceMemberPolygon() {
        return new MultiSurface.SurfaceMember.Polygon();
    }

    /**
     * Create an instance of {@link com.astrium.hmas.bean.catalogue.Polygon.Exterior.LinearRing.PosList }
     * 
     */
    public com.astrium.hmas.bean.catalogue.Polygon.Exterior.LinearRing.PosList createPolygonExteriorLinearRingPosList() {
        return new com.astrium.hmas.bean.catalogue.Polygon.Exterior.LinearRing.PosList();
    }

    /**
     * Create an instance of {@link com.astrium.hmas.bean.catalogue.Polygon.Exterior }
     * 
     */
    public com.astrium.hmas.bean.catalogue.Polygon.Exterior createPolygonExterior() {
        return new com.astrium.hmas.bean.catalogue.Polygon.Exterior();
    }

    /**
     * Create an instance of {@link EarthObservation }
     * 
     */
    public EarthObservation createEarthObservation() {
        return new EarthObservation();
    }

    /**
     * Create an instance of {@link com.astrium.hmas.bean.catalogue.Polygon.Exterior.LinearRing }
     * 
     */
    public com.astrium.hmas.bean.catalogue.Polygon.Exterior.LinearRing createPolygonExteriorLinearRing() {
        return new com.astrium.hmas.bean.catalogue.Polygon.Exterior.LinearRing();
    }

    /**
     * Create an instance of {@link EarthObservationEquipment }
     * 
     */
    public EarthObservationEquipment createEarthObservationEquipment() {
        return new EarthObservationEquipment();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "date")
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<String>(_Date_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "itemsPerPage")
    public JAXBElement<Short> createItemsPerPage(Short value) {
        return new JAXBElement<Short>(_ItemsPerPage_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "startIndex")
    public JAXBElement<Short> createStartIndex(Short value) {
        return new JAXBElement<Short>(_StartIndex_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "totalResults")
    public JAXBElement<Short> createTotalResults(Short value) {
        return new JAXBElement<Short>(_TotalResults_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing.ProcessingInformation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/eop/2.0", name = "ProcessingInformation", scope = EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing.class)
    public JAXBElement<EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing.ProcessingInformation> createEarthObservationMetaDataPropertyEarthObservationMetaDataProcessingProcessingInformation(EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing.ProcessingInformation value) {
        return new JAXBElement<EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing.ProcessingInformation>(_EarthObservationMetaDataPropertyEarthObservationMetaDataProcessingProcessingInformation_QNAME, EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing.ProcessingInformation.class, EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing.class, value);
    }

}
