//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.12 at 11:15:35 AM BST 
//


package com.astrium.hmas.bean.catalogue;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="platform" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Platform" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="shortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="orbitType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="instrument" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Instrument" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="shortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sensor" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Sensor" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="sensorType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="operationalMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="resolution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="swathIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="wavelengthInformation" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="WavelengthInformation" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="discreteWavelengths" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                 &lt;element name="spectralRange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="acquisitionParameters" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Acquisition" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="orbitNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="orbitDirection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="wrsLongitudeGrid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="wrsLatitudeGrid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.opengis.net/gml/3.2}id"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "platform",
    "instrument",
    "sensor",
    "acquisitionParameters"
})
@XmlRootElement(name = "EarthObservationEquipment", namespace = "http://www.opengis.net/eop/2.0")
public class EarthObservationEquipment {

    @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
    protected EarthObservationEquipment.Platform platform;
    @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
    protected EarthObservationEquipment.Instrument instrument;
    @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
    protected EarthObservationEquipment.Sensor sensor;
    @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
    protected EarthObservationEquipment.AcquisitionParameters acquisitionParameters;
    @XmlAttribute(namespace = "http://www.opengis.net/gml/3.2")
    protected String id;

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link EarthObservationEquipment.Platform }
     *     
     */
    public EarthObservationEquipment.Platform getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link EarthObservationEquipment.Platform }
     *     
     */
    public void setPlatform(EarthObservationEquipment.Platform value) {
        this.platform = value;
    }

    /**
     * Gets the value of the instrument property.
     * 
     * @return
     *     possible object is
     *     {@link EarthObservationEquipment.Instrument }
     *     
     */
    public EarthObservationEquipment.Instrument getInstrument() {
        return instrument;
    }

    /**
     * Sets the value of the instrument property.
     * 
     * @param value
     *     allowed object is
     *     {@link EarthObservationEquipment.Instrument }
     *     
     */
    public void setInstrument(EarthObservationEquipment.Instrument value) {
        this.instrument = value;
    }

    /**
     * Gets the value of the sensor property.
     * 
     * @return
     *     possible object is
     *     {@link EarthObservationEquipment.Sensor }
     *     
     */
    public EarthObservationEquipment.Sensor getSensor() {
        return sensor;
    }

    /**
     * Sets the value of the sensor property.
     * 
     * @param value
     *     allowed object is
     *     {@link EarthObservationEquipment.Sensor }
     *     
     */
    public void setSensor(EarthObservationEquipment.Sensor value) {
        this.sensor = value;
    }

    /**
     * Gets the value of the acquisitionParameters property.
     * 
     * @return
     *     possible object is
     *     {@link EarthObservationEquipment.AcquisitionParameters }
     *     
     */
    public EarthObservationEquipment.AcquisitionParameters getAcquisitionParameters() {
        return acquisitionParameters;
    }

    /**
     * Sets the value of the acquisitionParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link EarthObservationEquipment.AcquisitionParameters }
     *     
     */
    public void setAcquisitionParameters(EarthObservationEquipment.AcquisitionParameters value) {
        this.acquisitionParameters = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Acquisition" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="orbitNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="orbitDirection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="wrsLongitudeGrid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="wrsLatitudeGrid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "acquisition"
    })
    public static class AcquisitionParameters {

        @XmlElement(name = "Acquisition", namespace = "http://www.opengis.net/eop/2.0")
        protected EarthObservationEquipment.AcquisitionParameters.Acquisition acquisition;

        /**
         * Gets the value of the acquisition property.
         * 
         * @return
         *     possible object is
         *     {@link EarthObservationEquipment.AcquisitionParameters.Acquisition }
         *     
         */
        public EarthObservationEquipment.AcquisitionParameters.Acquisition getAcquisition() {
            return acquisition;
        }

        /**
         * Sets the value of the acquisition property.
         * 
         * @param value
         *     allowed object is
         *     {@link EarthObservationEquipment.AcquisitionParameters.Acquisition }
         *     
         */
        public void setAcquisition(EarthObservationEquipment.AcquisitionParameters.Acquisition value) {
            this.acquisition = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="orbitNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="orbitDirection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="wrsLongitudeGrid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="wrsLatitudeGrid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "orbitNumber",
            "orbitDirection",
            "wrsLongitudeGrid",
            "wrsLatitudeGrid"
        })
        public static class Acquisition {

            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected String orbitNumber;
            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected String orbitDirection;
            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected String wrsLongitudeGrid;
            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected String wrsLatitudeGrid;

            /**
             * Gets the value of the orbitNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrbitNumber() {
                return orbitNumber;
            }

            /**
             * Sets the value of the orbitNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrbitNumber(String value) {
                this.orbitNumber = value;
            }

            /**
             * Gets the value of the orbitDirection property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrbitDirection() {
                return orbitDirection;
            }

            /**
             * Sets the value of the orbitDirection property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrbitDirection(String value) {
                this.orbitDirection = value;
            }

            /**
             * Gets the value of the wrsLongitudeGrid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWrsLongitudeGrid() {
                return wrsLongitudeGrid;
            }

            /**
             * Sets the value of the wrsLongitudeGrid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWrsLongitudeGrid(String value) {
                this.wrsLongitudeGrid = value;
            }

            /**
             * Gets the value of the wrsLatitudeGrid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWrsLatitudeGrid() {
                return wrsLatitudeGrid;
            }

            /**
             * Sets the value of the wrsLatitudeGrid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWrsLatitudeGrid(String value) {
                this.wrsLatitudeGrid = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Instrument" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="shortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "instrument"
    })
    public static class Instrument {

        @XmlElement(name = "Instrument", namespace = "http://www.opengis.net/eop/2.0")
        protected EarthObservationEquipment.Instrument.InstrumentType instrument;

        /**
         * Gets the value of the instrument property.
         * 
         * @return
         *     possible object is
         *     {@link EarthObservationEquipment.Instrument.Instrument }
         *     
         */
        public EarthObservationEquipment.Instrument.InstrumentType getInstrument() {
            return instrument;
        }

        /**
         * Sets the value of the instrument property.
         * 
         * @param value
         *     allowed object is
         *     {@link EarthObservationEquipment.Instrument.Instrument }
         *     
         */
        public void setInstrument(EarthObservationEquipment.Instrument.InstrumentType value) {
            this.instrument = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="shortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "shortName"
        })
        public static class InstrumentType {

            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected String shortName;

            /**
             * Gets the value of the shortName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShortName() {
                return shortName;
            }

            /**
             * Sets the value of the shortName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShortName(String value) {
                this.shortName = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Platform" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="shortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="orbitType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "platform"
    })
    public static class Platform {

        @XmlElement(name = "Platform", namespace = "http://www.opengis.net/eop/2.0")
        protected EarthObservationEquipment.Platform.PlatformType platform;

        /**
         * Gets the value of the platform property.
         * 
         * @return
         *     possible object is
         *     {@link EarthObservationEquipment.Platform.Platform }
         *     
         */
        public EarthObservationEquipment.Platform.PlatformType getPlatform() {
            return platform;
        }

        /**
         * Sets the value of the platform property.
         * 
         * @param value
         *     allowed object is
         *     {@link EarthObservationEquipment.Platform.Platform }
         *     
         */
        public void setPlatform(EarthObservationEquipment.Platform.PlatformType value) {
            this.platform = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="shortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="orbitType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "shortName",
            "orbitType"
        })
        public static class PlatformType {

            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected String shortName;
            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected String orbitType;

            /**
             * Gets the value of the shortName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShortName() {
                return shortName;
            }

            /**
             * Sets the value of the shortName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShortName(String value) {
                this.shortName = value;
            }

            /**
             * Gets the value of the orbitType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrbitType() {
                return orbitType;
            }

            /**
             * Sets the value of the orbitType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrbitType(String value) {
                this.orbitType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Sensor" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="sensorType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="operationalMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="resolution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="swathIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="wavelengthInformation" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="WavelengthInformation" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="discreteWavelengths" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                       &lt;element name="spectralRange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sensor"
    })
    public static class Sensor {

        @XmlElement(name = "Sensor", namespace = "http://www.opengis.net/eop/2.0")
        protected EarthObservationEquipment.Sensor.SensorType sensor;

        /**
         * Gets the value of the sensor property.
         * 
         * @return
         *     possible object is
         *     {@link EarthObservationEquipment.Sensor.Sensor }
         *     
         */
        public EarthObservationEquipment.Sensor.SensorType getSensor() {
            return sensor;
        }

        /**
         * Sets the value of the sensor property.
         * 
         * @param value
         *     allowed object is
         *     {@link EarthObservationEquipment.Sensor.Sensor }
         *     
         */
        public void setSensor(EarthObservationEquipment.Sensor.SensorType value) {
            this.sensor = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="sensorType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="operationalMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="resolution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="swathIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="wavelengthInformation" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="WavelengthInformation" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="discreteWavelengths" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                             &lt;element name="spectralRange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sensorType",
            "operationalMode",
            "resolution",
            "swathIdentifier",
            "wavelengthInformation"
        })
        public static class SensorType {

            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected String sensorType;
            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected String operationalMode;
            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected String resolution;
            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected String swathIdentifier;
            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected EarthObservationEquipment.Sensor.SensorType.WavelengthInformation wavelengthInformation;

            /**
             * Gets the value of the sensorType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSensorType() {
                return sensorType;
            }

            /**
             * Sets the value of the sensorType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSensorType(String value) {
                this.sensorType = value;
            }

            /**
             * Gets the value of the operationalMode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOperationalMode() {
                return operationalMode;
            }

            /**
             * Sets the value of the operationalMode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOperationalMode(String value) {
                this.operationalMode = value;
            }

            /**
             * Gets the value of the resolution property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getResolution() {
                return resolution;
            }

            /**
             * Sets the value of the resolution property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setResolution(String value) {
                this.resolution = value;
            }

            /**
             * Gets the value of the swathIdentifier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSwathIdentifier() {
                return swathIdentifier;
            }

            /**
             * Sets the value of the swathIdentifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSwathIdentifier(String value) {
                this.swathIdentifier = value;
            }

            /**
             * Gets the value of the wavelengthInformation property.
             * 
             * @return
             *     possible object is
             *     {@link EarthObservationEquipment.Sensor.Sensor.WavelengthInformation }
             *     
             */
            public EarthObservationEquipment.Sensor.SensorType.WavelengthInformation getWavelengthInformation() {
                return wavelengthInformation;
            }

            /**
             * Sets the value of the wavelengthInformation property.
             * 
             * @param value
             *     allowed object is
             *     {@link EarthObservationEquipment.Sensor.Sensor.WavelengthInformation }
             *     
             */
            public void setWavelengthInformation(EarthObservationEquipment.Sensor.SensorType.WavelengthInformation value) {
                this.wavelengthInformation = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="WavelengthInformation" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="discreteWavelengths" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                   &lt;element name="spectralRange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "wavelengthInformation"
            })
            public static class WavelengthInformation {

                @XmlElement(name = "WavelengthInformation", namespace = "http://www.opengis.net/eop/2.0")
                protected EarthObservationEquipment.Sensor.SensorType.WavelengthInformation.WavelengthInformationType wavelengthInformation;

                /**
                 * Gets the value of the wavelengthInformation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link EarthObservationEquipment.Sensor.Sensor.WavelengthInformation.WavelengthInformation }
                 *     
                 */
                public EarthObservationEquipment.Sensor.SensorType.WavelengthInformation.WavelengthInformationType getWavelengthInformation() {
                    return wavelengthInformation;
                }

                /**
                 * Sets the value of the wavelengthInformation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link EarthObservationEquipment.Sensor.Sensor.WavelengthInformation.WavelengthInformation }
                 *     
                 */
                public void setWavelengthInformation(EarthObservationEquipment.Sensor.SensorType.WavelengthInformation.WavelengthInformationType value) {
                    this.wavelengthInformation = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="discreteWavelengths" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *         &lt;element name="spectralRange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "discreteWavelengths",
                    "spectralRange"
                })
                public static class WavelengthInformationType {

                    @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
                    protected String discreteWavelengths;
                    @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
                    protected String spectralRange;

                    /**
                     * Gets the value of the discreteWavelengths property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDiscreteWavelengths() {
                        return discreteWavelengths;
                    }

                    /**
                     * Sets the value of the discreteWavelengths property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDiscreteWavelengths(String value) {
                        this.discreteWavelengths = value;
                    }

                    /**
                     * Gets the value of the spectralRange property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getSpectralRange() {
                        return spectralRange;
                    }

                    /**
                     * Sets the value of the spectralRange property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setSpectralRange(String value) {
                        this.spectralRange = value;
                    }

                }

            }

        }

    }

}
