//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 11:07:48 AM BST 
//


package com.astrium.hmas.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/om/2.0}phenomenonTime" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/om/2.0}resultTime" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/om/2.0}procedure" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/om/2.0}observedProperty" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/om/2.0}featureOfInterest" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/om/2.0}result" minOccurs="0"/>
 *         &lt;element name="metaDataProperty" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EarthObservationMetaData" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="acquisitionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="productType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="downlinkedTo" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="DownlinkInformation" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="acquisitionStation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="processing" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ProcessingInformation" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="processingCenter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.opengis.net/gml/3.2}id"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "phenomenonTime",
    "resultTime",
    "procedure",
    "observedProperty",
    "featureOfInterest",
    "result",
    "metaDataProperty"
})
@XmlRootElement(name = "EarthObservation", namespace = "http://www.opengis.net/eop/2.0")
public class EarthObservation {

    protected PhenomenonTime phenomenonTime;
    protected ResultTime resultTime;
    protected Procedure procedure;
    protected ObservedProperty observedProperty;
    protected FeatureOfInterest featureOfInterest;
    protected Object result;
    @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
    protected EarthObservation.MetaDataProperty metaDataProperty;
    @XmlAttribute(name = "id", namespace = "http://www.opengis.net/gml/3.2")
    protected String id;

    /**
     * Gets the value of the phenomenonTime property.
     * 
     * @return
     *     possible object is
     *     {@link PhenomenonTime }
     *     
     */
    public PhenomenonTime getPhenomenonTime() {
        return phenomenonTime;
    }

    /**
     * Sets the value of the phenomenonTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhenomenonTime }
     *     
     */
    public void setPhenomenonTime(PhenomenonTime value) {
        this.phenomenonTime = value;
    }

    /**
     * Gets the value of the resultTime property.
     * 
     * @return
     *     possible object is
     *     {@link ResultTime }
     *     
     */
    public ResultTime getResultTime() {
        return resultTime;
    }

    /**
     * Sets the value of the resultTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultTime }
     *     
     */
    public void setResultTime(ResultTime value) {
        this.resultTime = value;
    }

    /**
     * Gets the value of the procedure property.
     * 
     * @return
     *     possible object is
     *     {@link Procedure }
     *     
     */
    public Procedure getProcedure() {
        return procedure;
    }

    /**
     * Sets the value of the procedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Procedure }
     *     
     */
    public void setProcedure(Procedure value) {
        this.procedure = value;
    }

    /**
     * Gets the value of the observedProperty property.
     * 
     * @return
     *     possible object is
     *     {@link ObservedProperty }
     *     
     */
    public ObservedProperty getObservedProperty() {
        return observedProperty;
    }

    /**
     * Sets the value of the observedProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservedProperty }
     *     
     */
    public void setObservedProperty(ObservedProperty value) {
        this.observedProperty = value;
    }

    /**
     * Gets the value of the featureOfInterest property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureOfInterest }
     *     
     */
    public FeatureOfInterest getFeatureOfInterest() {
        return featureOfInterest;
    }

    /**
     * Sets the value of the featureOfInterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureOfInterest }
     *     
     */
    public void setFeatureOfInterest(FeatureOfInterest value) {
        this.featureOfInterest = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setResult(Object value) {
        this.result = value;
    }

    /**
     * Gets the value of the metaDataProperty property.
     * 
     * @return
     *     possible object is
     *     {@link EarthObservation.MetaDataProperty }
     *     
     */
    public EarthObservation.MetaDataProperty getMetaDataProperty() {
        return metaDataProperty;
    }

    /**
     * Sets the value of the metaDataProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link EarthObservation.MetaDataProperty }
     *     
     */
    public void setMetaDataProperty(EarthObservation.MetaDataProperty value) {
        this.metaDataProperty = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EarthObservationMetaData" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="acquisitionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="productType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="downlinkedTo" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="DownlinkInformation" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="acquisitionStation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="processing" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ProcessingInformation" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="processingCenter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "earthObservationMetaData"
    })
    public static class MetaDataProperty {

        @XmlElement(name = "EarthObservationMetaData", namespace = "http://www.opengis.net/eop/2.0")
        protected EarthObservation.MetaDataProperty.EarthObservationMetaData earthObservationMetaData;

        /**
         * Gets the value of the earthObservationMetaData property.
         * 
         * @return
         *     possible object is
         *     {@link EarthObservation.MetaDataProperty.EarthObservationMetaData }
         *     
         */
        public EarthObservation.MetaDataProperty.EarthObservationMetaData getEarthObservationMetaData() {
            return earthObservationMetaData;
        }

        /**
         * Sets the value of the earthObservationMetaData property.
         * 
         * @param value
         *     allowed object is
         *     {@link EarthObservation.MetaDataProperty.EarthObservationMetaData }
         *     
         */
        public void setEarthObservationMetaData(EarthObservation.MetaDataProperty.EarthObservationMetaData value) {
            this.earthObservationMetaData = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="acquisitionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="productType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="downlinkedTo" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="DownlinkInformation" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="acquisitionStation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="processing" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ProcessingInformation" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="processingCenter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "identifier",
            "acquisitionType",
            "productType",
            "status",
            "downlinkedTo",
            "processing"
        })
        public static class EarthObservationMetaData {

            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected String identifier;
            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected String acquisitionType;
            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected String productType;
            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected String status;
            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected EarthObservation.MetaDataProperty.EarthObservationMetaData.DownlinkedTo downlinkedTo;
            @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
            protected EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing processing;

            /**
             * Gets the value of the identifier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdentifier() {
                return identifier;
            }

            /**
             * Sets the value of the identifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdentifier(String value) {
                this.identifier = value;
            }

            /**
             * Gets the value of the acquisitionType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAcquisitionType() {
                return acquisitionType;
            }

            /**
             * Sets the value of the acquisitionType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAcquisitionType(String value) {
                this.acquisitionType = value;
            }

            /**
             * Gets the value of the productType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductType() {
                return productType;
            }

            /**
             * Sets the value of the productType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductType(String value) {
                this.productType = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatus() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatus(String value) {
                this.status = value;
            }

            /**
             * Gets the value of the downlinkedTo property.
             * 
             * @return
             *     possible object is
             *     {@link EarthObservation.MetaDataProperty.EarthObservationMetaData.DownlinkedTo }
             *     
             */
            public EarthObservation.MetaDataProperty.EarthObservationMetaData.DownlinkedTo getDownlinkedTo() {
                return downlinkedTo;
            }

            /**
             * Sets the value of the downlinkedTo property.
             * 
             * @param value
             *     allowed object is
             *     {@link EarthObservation.MetaDataProperty.EarthObservationMetaData.DownlinkedTo }
             *     
             */
            public void setDownlinkedTo(EarthObservation.MetaDataProperty.EarthObservationMetaData.DownlinkedTo value) {
                this.downlinkedTo = value;
            }

            /**
             * Gets the value of the processing property.
             * 
             * @return
             *     possible object is
             *     {@link EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing }
             *     
             */
            public EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing getProcessing() {
                return processing;
            }

            /**
             * Sets the value of the processing property.
             * 
             * @param value
             *     allowed object is
             *     {@link EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing }
             *     
             */
            public void setProcessing(EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing value) {
                this.processing = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="DownlinkInformation" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="acquisitionStation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "downlinkInformation"
            })
            public static class DownlinkedTo {

                @XmlElement(name = "DownlinkInformation", namespace = "http://www.opengis.net/eop/2.0")
                protected EarthObservation.MetaDataProperty.EarthObservationMetaData.DownlinkedTo.DownlinkInformation downlinkInformation;

                /**
                 * Gets the value of the downlinkInformation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link EarthObservation.MetaDataProperty.EarthObservationMetaData.DownlinkedTo.DownlinkInformation }
                 *     
                 */
                public EarthObservation.MetaDataProperty.EarthObservationMetaData.DownlinkedTo.DownlinkInformation getDownlinkInformation() {
                    return downlinkInformation;
                }

                /**
                 * Sets the value of the downlinkInformation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link EarthObservation.MetaDataProperty.EarthObservationMetaData.DownlinkedTo.DownlinkInformation }
                 *     
                 */
                public void setDownlinkInformation(EarthObservation.MetaDataProperty.EarthObservationMetaData.DownlinkedTo.DownlinkInformation value) {
                    this.downlinkInformation = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="acquisitionStation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "acquisitionStation"
                })
                public static class DownlinkInformation {

                    @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
                    protected String acquisitionStation;

                    /**
                     * Gets the value of the acquisitionStation property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getAcquisitionStation() {
                        return acquisitionStation;
                    }

                    /**
                     * Sets the value of the acquisitionStation property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setAcquisitionStation(String value) {
                        this.acquisitionStation = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ProcessingInformation" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="processingCenter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "processingInformation"
            })
            public static class Processing {

                @XmlElement(name = "ProcessingInformation", namespace = "http://www.opengis.net/eop/2.0")
                protected EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing.ProcessingInformation processingInformation;

                /**
                 * Gets the value of the processingInformation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing.ProcessingInformation }
                 *     
                 */
                public EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing.ProcessingInformation getProcessingInformation() {
                    return processingInformation;
                }

                /**
                 * Sets the value of the processingInformation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing.ProcessingInformation }
                 *     
                 */
                public void setProcessingInformation(EarthObservation.MetaDataProperty.EarthObservationMetaData.Processing.ProcessingInformation value) {
                    this.processingInformation = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="processingCenter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "processingCenter"
                })
                public static class ProcessingInformation {

                    @XmlElement(namespace = "http://www.opengis.net/eop/2.0")
                    protected String processingCenter;

                    /**
                     * Gets the value of the processingCenter property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getProcessingCenter() {
                        return processingCenter;
                    }

                    /**
                     * Sets the value of the processingCenter property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setProcessingCenter(String value) {
                        this.processingCenter = value;
                    }

                }

            }

        }

    }

}
