//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 11:07:48 AM BST 
//
/*@XmlSchema(
    elementFormDefault=XmlNsForm.QUALIFIED,
    namespace="http://www.example.com/FOO",
    xmlns={@XmlNs(prefix="bar", 
                  namespaceURI="http://www.example.com/BAR")}
)*/
@javax.xml.bind.annotation.XmlSchema(
		namespace = "http://www.opengis.net/om/2.0", 
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
		attributeFormDefault = javax.xml.bind.annotation.XmlNsForm.UNQUALIFIED,
		xmlns={@XmlNs(prefix="time", 
        namespaceURI="http://a9.com/-/opensearch/extensions/time/1.0/"),
        @XmlNs(prefix="os", 
        namespaceURI="http://a9.com/-/spec/opensearch/1.1/"),
        @XmlNs(prefix="dc", 
        namespaceURI="http://purl.org/dc/elements/1.1/"),
        @XmlNs(prefix="georss", 
        namespaceURI="http://www.georss.org/georss"),
        @XmlNs(prefix="gml", 
        namespaceURI="http://www.opengis.net/gml/3.2"),
        @XmlNs(prefix="gml", 
        namespaceURI="http://www.opengis.net/gml"),
        @XmlNs(prefix="geo", 
        namespaceURI="http://a9.com/-/opensearch/extensions/geo/1.0/"),
        @XmlNs(prefix="eop", 
        namespaceURI="http://www.opengis.net/eop/2.0"),
        @XmlNs(prefix="xlink", 
        namespaceURI="http://www.w3.org/1999/xlink"),
        @XmlNs(prefix="swe", 
        namespaceURI="http://www.opengis.net/swe/1.0"),
        @XmlNs(prefix="om", 
        namespaceURI="http://www.opengis.net/om/2.0"),
        @XmlNs(prefix="", 
        namespaceURI="http://www.w3.org/2005/Atom")})
package com.astrium.hmas.bean;
import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;
