//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 11:07:48 AM BST 
//


package com.astrium.hmas.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/eop/2.0}EarthObservationEquipment" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "earthObservationEquipment"
})
@XmlRootElement(name = "procedure")
public class Procedure {

    @XmlElement(name = "EarthObservationEquipment", namespace = "http://www.opengis.net/eop/2.0")
    protected EarthObservationEquipment earthObservationEquipment;

    /**
     * Gets the value of the earthObservationEquipment property.
     * 
     * @return
     *     possible object is
     *     {@link EarthObservationEquipment }
     *     
     */
    public EarthObservationEquipment getEarthObservationEquipment() {
        return earthObservationEquipment;
    }

    /**
     * Sets the value of the earthObservationEquipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link EarthObservationEquipment }
     *     
     */
    public void setEarthObservationEquipment(EarthObservationEquipment value) {
        this.earthObservationEquipment = value;
    }

}
